# Generated by Django 2.0.2 on 2018-04-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_list_app', '0002_comicslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicslist',
            name='volume',
            field=models.IntegerField(default=1),
        ),
    ]
